### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by jmhuculak** [UVicLibrary/Spotlight2_custom#1]
http://spotlight.library.uvic.ca/spotlight/library-publications/feature/test

**Comment by eltiffster** [comment]
Extra whitespace above objects. Fixed in `_open_seadragon` by deleting `height: min-content` in style tag.

Multiple embed videos not working.

**Comment by eltiffster** [comment]
We had some special code for the [audio compound object](http://spotlight.library.uvic.ca/spotlight/wwi/catalog/1-32) in the wwi exhibit that overcorrected: it hid additional A/V players any time there was more than one on the page. That's why they wouldn't show when embedded into feature pages.

I added an extra conditional in `_openseadragon_default.html.erb` for the custom code: 
```ruby
<% if @resource.file_type == "compound object" && (@resource.file_name.include?("mp3") if @resource.file_name) %>
```
